### ISSUE TITLE
Share source code

### ISSUE THREAD

**Issue by Lazys** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#16]
Hi,
can you share source code of the extension? We would be able to fork it then and make some additional improvements/bug fixes.

We would really appreciate this.

**Comment by edtro** [comment]
Unfortunately I am not able to this at the moment. I have created this project completely in my free spare time, I have however released this project under the name of my current employer. So I have an issue regarding IP.

**Comment by Lazys** [comment]
Ok, I see.

**Comment by StingyJack** [comment]
@edtro - If you made this as part of a work effort defined or assigned by your employer, then this is considered by most of the world ([Belgium](https://www.law-right.com/intellectual-property-rights-in-software/#:~:text=Copyright%20protection%20of%20software%20is,Act%20of%2030%20June%201994.&text=In%20the%20case%20of%20software%20created%20by%20an%20employee%20in,seventy%2Dfive%20years%20from%20publication.), UK, EU, US, other Berne convention members) as a "work-for-hire", and your employer owns it (because they paid you to create it).

Whom its "released by" doesnt change a copyright authorship. It looks to me like you are just donating some advertising space on your program to your employer - which would not transfer ownership. Unless you have some signed agreement that names this work that transfers the copyright to your employer, **the copyright belongs to you**.   

OFC do your own research (i'm just a stranger on the internet), but everyone in our line of work should definitely be aware of the actual law in this regard. There are too many predatory or unscrupulous corporations for us to be ignorant about it. 

If you find that my understanding is correct, but still do not want to share this, I would like to think your decision would be respected here of all places (as @Lazys does). Dont let anyone "OSS shame" you into sharing it if you dont want to . Thats as bad as a corporation trying to assert ownership of your work.

Thanks for the extension, btw. It was what I needed, when I needed it.
