### ISSUE TITLE
Bug: Columns for custom states are not displayed

### ISSUE THREAD

**Issue by Lazys** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#17]
We have in our company added few custom states to the work items, but it looks like that appropriate columns for this states are not displayed even if there are some work items which should be displayed.

Also we have query where we display work items according to the rules:
![image](https://user-images.githubusercontent.com/21179961/81974068-53aca080-9625-11ea-9ada-7802523d1c00.png)
and work items from the second group (based on the changed date and changed by fields) are also not displayed on the board.

**Comment by edtro** [comment]
For the first issue I really need more information. Is your Org online or onprem? Are you using the old XML witd or are you using the new inheritance types? Are you getting errors in the console.log() ? Are you using the config hub? Is it a taskboard or kanban?
 
Because when I test it... just tested on an onprem (and the project is using the old XML witd) and it works fine. 

Just to let you know: when you are not using the config hub, then automatically a check is done, to see what item types are within the resultset of the query. The workitem type is retrieved from the REST api with the call client.getWorkItemType()... that use this REST api call https://docs.microsoft.com/en-us/rest/api/azure/devops/processes/work%20item%20types/get?view=azure-devops-rest-5.1#getworkitemtypeexpand 

Kr
Edward

**Comment by edtro** [comment]
The second issue... this I will have to investigate.

**Comment by edtro** [comment]
I have investigated the second issue... on an online org btw (so I could not use @Today - 1... instead of this I have used the new @StartOfDay('-1d') that has replaced this)... and I did not have any problems. So I need more information.

Tips: did you edit the query in the editor? and did you save it? If you do not save it... QBB will show cards based on the old definition. Please make sure you save it... next to this make sure the item is within the actual resultset.

**Comment by Lazys** [comment]
1. Console.log is clear.
2. We're using online organization
3. We have our own process inherited from the "Scrum" process
4. Kanban
5. I didn't touch config, I've just installed your new extension and run query.

So I have the same query which I run in your old extension:
![image](https://user-images.githubusercontent.com/21179961/82203135-2c92ef00-9903-11ea-80c7-0ca3149e257f.png)

And in the one one:
![image](https://user-images.githubusercontent.com/21179961/82203205-46cccd00-9903-11ea-9b66-8d41b5c59016.png)

**Comment by edtro** [comment]
Hi, thanks for the extra information. It seems that it has something to do with the new extra states. 
Strange, because I am retrieving them with the REST api... I will have to look into this. Keep you posted.
Kr.
Edward

**Comment by Lazys** [comment]
Thanks, waiting for info :)

**Comment by edtro** [comment]
So I have the following query and config setup:
![tst](https://user-images.githubusercontent.com/27762373/82226067-4e519d80-9926-11ea-886e-a26072078d1a.png)

The Console.log() displayes the following:
`Config loaded: {"fields":[],"columns":[]}`

The REST api is getting the following (after I have added a bunch of states to the Epic):
Epic
```json
[
{"name":"New","color":"b2b2b2","category":"Proposed"},
{"name":"Active","color":"007acc","category":"InProgress"},
{"name":"Resolved","color":"007acc","category":"InProgress"},
{"name":"Testing","color":"5688E0","category":"InProgress"},
{"name":"To be tested","color":"5688E0","category":"InProgress"},
{"name":"To be approved","color":"5688E0","category":"InProgress"},
{"name":"Approved","color":"5688E0","category":"InProgress"},
{"name":"To be deployed","color":"5688E0","category":"InProgress"},
{"name":"Deployed","color":"4E9D5D","category":"Completed"},
{"name":"Removed","color":"ffffff","category":"Removed"}
]
```
Feature
```json
[
{"name":"New","color":"b2b2b2","category":"Proposed"},
{"name":"Active","color":"007acc","category":"InProgress"},
{"name":"Resolved","color":"007acc","category":"InProgress"},
{"name":"Closed","color":"339933","category":"Completed"},
{"name":"Removed","color":"ffffff","category":"Removed"}
]
```
etc…

So I am retrieving the correct states… and within my board I am getting the expected results.
I also had an earlier reported bug regarding multiple teamprojects… that custo, states specific for a certain teamproject were not displayed, so I am getting the types now per teamproject (that resolved the previous issue).

**So I cannot reproduce this issue. It looks like that everything is working fine and as expected.**

The only way I got a similar situation within my board, that was when I had configuration settings defining the columns (and I had only setup the default columns).
 
So can you please make sure, you have no configuration settings activated (check the console like aboce to be sure) and check the REST api if you are getting the correct states (use ‘…/_apis/wit/workitemtypes/{type}?api-version=5.1 see the reference: https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work%20item%20types/get?view=azure-devops-rest-5.1’)

Because I cannot reproduce this issue, it is really difficult to try to resolve this issue. I am however very determined to resolve this.

**Comment by Lazys** [comment]
Thanks for detemination, I'm really impressed.

In the console.log I have only:

![image](https://user-images.githubusercontent.com/21179961/82291235-eabc8400-99a8-11ea-99e7-dc7644daf99c.png)

But I guess that failed loading source maps shouldn't be a problem here. But I didn't see any 
`Config loaded: {"fields":[],"columns":[]}`
as you described and as I said we didn't touch yours extension config in the project settings, but I checked this to be sure and it's empty (even without braces {}).

I didn't mention this earlier, but in fact our query is across projects.

**Comment by edtro** [comment]
Eureka! I think I have found the issue... Please can you check within the the definition of the work item type, for the custom stype what 'category' you have filled in? Thanks in advance. 

(I am hoping that your answer will support my theory regarding the cause... and If I am right, I will be able to create a new version this evening)

**Comment by edtro** [comment]
Solved!
I have just released version 0.20140.  
Please feel free to check it out... Let me know if this solves your issues.
Kr
Edward

**Comment by Lazys** [comment]
Yep, it's working :) I'm really glad that you resolved this issue. Thanks for that! We're waiting for the new features ;)

**Comment by edtro** [comment]
Hi, thanks for the feedback.

I really appreciate that you have raised this issue. This was something that I have overlooked at first. This way I am able to get this extension really stable :-)

Kr
Edward

**Comment by Lazys** [comment]
Hehe, ok I'm glad to hear that :)
