### ISSUE TITLE
Dynamic sizing of column widths

### ISSUE THREAD

**Issue by cliveytech** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#22]
Please could you implement dynamic sizing of column widths to allow more than 1 card to show horizontally in columns when the users window size allows this?  

This would be really useful for us when we do a Kanban style standup (we have lots of cards in each team column)

**Comment by ChrisGibson1982** [comment]
i'd definitely be interested in this

**Comment by edtro** [comment]
Hi,
Thanks for the feedback. Great idea! 
But unfortunately I am not planning to implement this. To be honest, I do not know what the impact of this would be. But at least I will be looking into this, to figure out how I could implement this, so I have marked this issue as 'improvement' instead of 'wont fix', at the moment. But I wont be able to do this any time soon. 
Kr.
Edward

**Comment by edtro** [comment]
Hi,
I am working on this. Here is a screenshot of a preview:
![image](https://user-images.githubusercontent.com/27762373/102640321-92c24780-415a-11eb-8a57-7994a5202cd0.png)

Here I have setup the 'active' column to a width of 2 cards. It will be possible to setup the width up to 5 cards next to each other. This have to be done within the config json, so this means that this will not be done dynamically based on the screen resolution etc. etc. 

(I am however adjusting the height of the cards based on the highest one dynamically, to make it look nicer)

Kr
Edward

**Comment by cliveytech** [comment]
Excellent, thanks Edward. I'll have a look over Christmas..

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by edtro** [comment]
I am happy to inform you, that I have released this new feature. Because it is a part of setting up the columns within the config... this will be in PREVIEW
