### ISSUE TITLE
Bug - Cannot save board view as bookmark in the browser

### ISSUE THREAD

**Issue by Lazys** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#28]
Cannot save board view as bookmark in the browser.

What's related to that issue - we are also not able to share link to the board page.

For example, following link:
https://XYZ/_queries/realdolmen.EdTro-AzureDevOps-Extensions-QueryBasedBoards-Public.EdTro-AzureDevOps-Extensions-QueryBasedBoards.BoardTab/8a280e4a-c09c-41b6-bfee-b89e9d2f083a/
will open "Results" tab in the query instead of "Show as board" view.

**Comment by edtro** [comment]
Hi,
I am not sure if I am able to fix this. It looks like a shortcomming of the SDK/API. I have tried some things, but it looks like that this is happening when the current page within the browser is not within the context of the teamproject that is used within the url. It looks like that the extension still has to load at that point, so I always be too late. So I am really puzzled on how to solve this (if its possible?).

I am currently using the homepage of the teamproject (a readme.md or a wiki page) to share the URLS of the boards. This seems to work without any issues. Hope this helps.

Stay tuned... because I might be able to provide an other solution for this issue in the very near future :-)

**Comment by Lazys** [comment]
Interesting point is that in the previous extension from your company that worked well. Maybe that will help you somehow in the investigation.

**Comment by edtro** [comment]
I can see what you mean with the sample extension from Microsoft, the 'Contribution Guide'. Hmmmm. I will have to see.

**Comment by edtro** [comment]
Hi, 

I have tried to fix this, but unfortunately I couldn't find the rootcause of the problem. I have posted an issue here: https://github.com/microsoft/azure-devops-extension-sample/issues/58

**Comment by Lazys** [comment]
Ok, thx for info :)

**Comment by edtro** [comment]
I have tried creating an issue somewhere else: https://github.com/microsoft/azure-devops-extension-sdk/issues/36

**Comment by edtro** [comment]
@Lazys 
Hi,
I have tried to report this bug at Microsoft, but I am not getting any response.
I will be closing this issue however, because I cannot do anything about it. I will be monitoring the issues that I have created, if there is any response, I will reopen this one.

Thanks for reporting this issue however. Hopefully at some point we will get a solution.
Kr
Edward

**Comment by Lazys** [comment]
Sure. I'm not happy about it, but I entirely understand it :)
