### ISSUE TITLE
With some zoom levels the "Arrow control" to collapse the most right column is overlaid by the options button.

### ISSUE THREAD

**Issue by bewalterBL** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#36]
With some zoom levels the "Arrow control" to collapse the most right column is overlaid by the options button. The Screenshot below is taken with a zoom level of 100%. I tested it with Edge 87.0.664.75 and Vivaldi 3.5.2115.87 (based on Chromium 87.0.4280.142).
When the filters are activated it is no problem, because the Options button is then shown on a separate row with the filters. Maybe it would be better to always show the options button on a separate row.
 
![image](https://user-images.githubusercontent.com/75365667/103994958-0a9ef300-5198-11eb-93ab-9e675b722026.png)

**Comment by edtro** [comment]
Hi @bewalterBL 
Yes, this is a known limitation. Unfortunately I cannot find any way to insert these icons within the toolbar of Azure DevOps itself (just above my icons). And this problem is now more noticable, because I have added wiplimits like in the standard boards... so I had to adjust the position of the chevron button accordingly.

So I have provided a couple of solutions:
- You can always enable the filter (just add a config to the global config). When the filter is displayed, the icons are displayed within the filterbar.
- Now you can click also on the column name to collapse (this was something that was not possible previously)
- I have added some extra spacing, so you can always scroll to the right when this happens.

So I have done my best to address this problem. Hope this helps.

Kr
Edward

**Comment by bewalterBL** [comment]
Hey,
yes I already configured it to always show the filters. That's perfectly fine for me.
Didn't notice the scrolling to the right solution yet :-). But when you know it is also a good solution. 

Thanks for thinking that through.
Best
Bernhard

**Comment by edtro** [comment]
You're welcome :-) 
Kr
Edward
