### ISSUE TITLE
unable to import configuration for queries

### ISSUE THREAD

**Issue by Riziv-Johan** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#38]
I'm trying to import configuration for my queries, but the configuration does not get imported. For the global config on the other hand, I can see the imported config. 
Also, when I choose "Show all queries" in the extensions configuration tab, the queries do not appear.

**Comment by edtro** [comment]
Hi Johan,
Thanks for reaching out! Highly appreciated!
I will be looking into this as soon as I can.

But I will be needing some extra information (like what is the output within the dev console of the browser).
Because we know eachother in real life, you can sent me this to my email adres :-)

I will contact you.

Kr
Edward

**Comment by edtro** [comment]
@Riziv-Johan Hi Johan, I have released a new version (release 0.21044) that should fix this problem. Could you please try. Just let me know.
Kr
Edward
