### ISSUE TITLE
Feature Request: extend taskboard with "add task" (add child) UI capability 

### ISSUE THREAD

**Issue by fwboettger** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#66]
Similar to the standard / out of the box Boards, would be great to have the capability to add child work items (foremost tasks) directly from within the taskboard.

Best regards,
Frank

**Comment by edtro** [comment]
Hi,
I intentionally didn't  implement the feature to create workitems within the board, because you would expect the newly created item always to show after it is created. So I should know the complete context for the new workitem that it should be created within, this would require analysing the query itself... and that would imply a lot of (endless) options you can run into. 

Thats the reason why I am not planning to do any like this as of yet.

Kr
Edward
