### ISSUE TITLE
Swimlanes not working

### ISSUE THREAD

**Issue by wkamer** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#68]
Hello,

I put the json below in the config of the query, but the swimlanes are not shown.

```json
{
	"swimlanes": {
		"field": "Microsoft.VSTS.Common.ValueArea",
		"defaultValue": "Business",
		"values": [
			{
				"value": "Architectural",
				"title": "Architectural"
			},
			{
				"value": "Business",
				"title": "Business"
			}
		]
	}
}
```

I expect two lanes with the Epics spread over those two lanes with the corresponding value in de (default) Value Are field.

**Comment by edtro** [comment]
Hi,
Sorry for the late response, but I will be looking into this issue shortly (I have got some leave with the holidays).
Kr
Edward

**Comment by awojtas** [comment]
Same experience here on Azure DevOps 2020 on-premises, swimlanes not working, although the config is parsed and saved correctly

**Comment by edtro** [comment]
I will try it on a on-premise installation this week. 

within the On-Line version it works correctly, with the following setup:
 "swimlanes":{
      "field":"Microsoft.VSTS.CMMI.Blocked",
      "defaultValue": "No",
      "values":[
         {
            "value":"Yes",
            "title":"Is Blocked"
         }
      ]
   }

Please make sure it is a 'Flat query'... also please try an other field (e.g. the field Blocked from the example above).

Kr
Edward

**Comment by edtro** [comment]
Please also note what is mentioned within the config.md regarding swimlanes:

Important notice
When you configure the query to split up the columns into Doing/Done and/or use the swimlanes, be aware that this extension will also do updates to the workitem in other fields than just the 'System.State' field. We are using existing fields (or custom fields you have created yourself), but we only allow fields that are setup with "allowed values".

So make sure that:

The REST api can retrieve the "allowed values", see examples:
_apis/wit/workitemtypes/Bug/fields/Microsoft.VSTS.CMMI.Blocked?$expand=All&api-version=5.1 (this is a text based picklist)
_apis/wit/workitemtypes/Bug/fields/Microsoft.VSTS.Common.Priority?$expand=All&api-version=5.1 (this is a number based picklist))
(also fields of the type boolean are allowed, regardless that these have no "allowed values" within, but obviously the allowed values are True or False, so this is implemented)
Please mind uppercase and lowercase, it is case sensitive.
NOTE: for obvious reasons all system fields are not allowed to be used e.g. System.WorkItemType, because the risk is too high or they are system protected.

NOTE #2: make sure to implement rules when you want to use the doing/done columns to reset the 'done' value to 'false' on state change.

**Comment by edtro** [comment]
Dear,
I am closing this issue because I am not getting any response.
Please reopen this issue and add some extra informatie like I have requested before, so I can try to help you.
Kr
Edward
