### ISSUE TITLE
"New Item" in saved board

### ISSUE THREAD

**Issue by DRojas13** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#76]
Good afternoon,

I have been reviewing the reference material online and I have not been able to locate the json line to enable the "New Item" command button (or equivalent) in a saved query board. Is this possible within the current release? Thank you for your time and this extension has been a huge help.

Best regards,
Daniel Rojas

**Comment by edtro** [comment]
Dear,
Intentionally I did not implement the 'New item' button. Why???, you might ask? Because when you create a new work item, you will need to have enough context to actually show the new item when created within the board. Microsoft is able to have this context within the standard Boards, by means of the team/board setup. But within this extension I do not have any context other than the query (the wiql) itself. That is the main reason, why I am not implementing this feature. 

Kr
Edward
