### ISSUE TITLE
Feature timeline does not pull in features in the current PI

### ISSUE THREAD

**Issue by Alex-Morales** [edtro/EdTro.AzureDevOps.Extensions.querybasedboards#82]
Hi,
We have an issue where 2-3 teams don't get their features pulled into the feature timeline using the query based boards regardless of what state or fields are filled in. I've shown what is on the feature timeline and what is in the backlog.
![Screenshot 2023-08-23 091434](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/assets/39387749/aaa4174a-a874-40c0-9a76-73879f580a28)
![Screenshot 2023-08-23 091410](https://github.com/edtro/EdTro.AzureDevOps.Extensions.querybasedboards/assets/39387749/d980534f-0721-46c9-abaa-014cacbaf744)

**Comment by Alex-Morales** [comment]
Hi @edtro , when I brought this issue to Microsoft they were the ones that found this was a query based boards issue. What kind of issue would this fall under if it's not query based boards? https://developercommunity.visualstudio.com/t/Features-do-not-populate-in-feature-time/10446149#T-ND10447765

**Comment by edtro** [comment]
Dear,

I have reviewed the mentioned issue, but a couple of items are marked as private, so I am not able to see everything.

This is the first part of the response of Microsoft:

According to your description, it seems like this issue is happening on kind of Extension related to Boards. We suggest you can report this issue to extension side and see if there is an outage recently.

In other words: Microsoft is pointing to the extension itself.

There is however no mention regarding “Query Based Boards”. And to my knowledge my extension cannot interfere with other extensions in any way, because the extension framework that is provided by Microsoft does not allow this.

So please find the correct extension and reach out to the creators/maintainers of that extension.

Kr
Edward

**Comment by edtro** [comment]
I think it is this one: https://marketplace.visualstudio.com/items?itemName=ms-devlabs.workitem-feature-timeline-extension

Kr
Edward
